name = "BayesianAstro"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["Scott Carter"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.10"
CUDA = "5"
Distributions = "0.25"
FITSIO = "0.17"
Images = "0.26"
Optim = "1"
StaticArrays = "1"
StatsBase = "0.34"
